<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="../css/style.css">
  </head>
  <body>
    <header class="navbar">
      <div class="conteiner">
        <div class="row">
          <a class="brand" href="#">Анализатор страниц</a>
        </div>
        <div class="nav-block">
          <ul class="nav">
            <li class="active">
              <a href="#">Главная</a>
            </li>
            <li>
              <a href="#Websites">Сайты</a>
            </li>
          </ul>
        </div>
      </div>
    </header>  

    <div class="conteiner">
      <div class="row">
        <form action="" class="form-check">
          <h2 class="form-check-title">Анализатор страниц</h2>
          <h3 class="form-check-description">Бесплатно проверяйте сайты на SEO пригодность</h3>
          <div class="example"></div>
          <input type="text" class="input-block" placeholder="https//www.example.com">
          <div class="check-btn">
            <input type="submit" value="Проверить">
          </div>
        </form>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>